### PR TITLE
Search text

### PR DESCRIPTION
**Pull request by dagewa**
Simple change allows searching

however, does not yet allow next/previous for parameter names that appear multiple times, so is not a complete solution for #130 yet.

### CODE REVIEW

**Comment by dagewa** [comment]
This now has a "Find next" button and only highlights the currently found item.

**Comment by dagewa** [comment]
I intend to merge early next week if there are no requested changes

**Comment by luisodls** [comment]
testing from

https://github.com/ccp4/DUI/pull/158

**Comment by dagewa** [comment]
Thanks!

**Pull request merged**
